version: '3'
services:
    db:
        image: mariadb
        environment: 
            MYSQL_ROOT_PASSWORD: kea_db_pass
        volumes:
            - dhcp_mysql:/var/lib/mysql
        ports:
            - 3306:3306
    dhcpd:
        image: fsedano/kea_dhcp_server_docker_dhcpd:latest
        network_mode: host
        build: dhcp
        ports:
            - 8000:8000
    websvc:
        network_mode: host
        build: websvc
        volumes:
            - ./websvc/src:/app:delegated
        ports:
            - 8002:8002
        environment: 
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
            - PORT=8001
volumes:
    dhcp_mysql: