version: '3'
services:
    db:
        image: mariadb
        environment: 
            MYSQL_ROOT_PASSWORD: kea_db_pass
        volumes:
            - dhcp_mysql:/var/lib/mysql
    dhcpd:
        image: fsedano/kea_dhcp_server_docker_dhcpd:latest
        network_mode: host
        build: dhcp
        ports:
            - 8000:8000
        
volumes:
    dhcp_mysql: