name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build dhcp --tag kea-dhcp-server:$(date +%s)
